name    'justinstoller/ruby_build'
version '0.0.1'
source 'https://github.com/justinstoller/puppet-ruby_build'
author 'justinstoller'
license 'Apache License, Version 2.0'
summary 'Installs ruby-build and Rubies with it'
description 'Installs ruby-build and Rubies with it using VCSRepo'
project_page 'https://github.com/justinstoller/puppet-ruby_build'

dependency 'puppetlabs/git'
dependency 'nanliu/staging'
dependency 'puppetlabs/vcsrepo'
